// GABRIEL



TS.Include = [
  { name: 'loadingAnim' },
  { name: 'quant'       , path: TS.Config.Path.Quantcast    + 'quant.js' },
  { name: 'vquant'      , path: TS.Config.Path.Quantcast    + 'vquant.js' },
  { name: 's_code'      , path: TS.Config.Path.Omniture     + 's_code.js' },
  { name: 's_code'      , path: TS.Config.Path.Omniture     + 'snfl_code.js' },
  { name: 'livepass'    , path: TS.Config.Path.Conviva      + 'livepass.js' },
  { name: 'liverail'    , path: TS.Config.Path.Liverail     + 'LiverailAdManager.js' },

  { name: 'LiveRailVPAIDManager'    , path: TS.Config.Path.Services + 'LiveRailVPAIDManager.js' },
  { name: 'ConvivaService'          , path: TS.Config.Path.Services + 'OmnitureService.js' },
  { name: 'ConvivaService'          , path: TS.Config.Path.Services + 'ConvivaService.js' },
  { name: 'events'                  , path: TS.Config.Path.Utils    + 'Events.js' },
  { name: 'configService'           , path: TS.Config.Path.Services + 'configService.js' },
  { name: 'customRulesService'      , path: TS.Config.Path.Services + 'customRulesService.js' },
  { name: 'EffectiveMeasureService' , path: TS.Config.Path.Services + 'EffectiveMeasureService.js' },
  { name: 'LotameService'           , path: TS.Config.Path.Services + 'LotameService.js' },
  { name: 'AkamaiService'           , path: TS.Config.Path.Services + 'AkamaiService.js' },
  { name: 'AdtechService'           , path: TS.Config.Path.Services + 'AdtechService.js' },
  { name: 'FullscreenService'       , path: TS.Config.Path.Services + 'FullscreenService.js' },
  { name: 'HistoryService'          , path: TS.Config.Path.Services + 'HistoryService.js' },
  { name: 'VolumeController'        , path: TS.Config.Path.Services + 'VolumeController.js' },

  { name: 'channelService'      , path: TS.Config.Path.Services     + 'channelService.js' },
  { name: 'mrssService'         , path: TS.Config.Path.Services     + 'mrssService.js' },
  { name: 'comscoreService'     , path: TS.Config.Path.Services     + 'comscoreService.js' },
  { name: 'channelChecker'      , path: TS.Config.Path.Utils        + 'channelChecker.js' },
  { name: 'countryChecker'      , path: TS.Config.Path.Utils        + 'countryChecker.js' },
  { name: 'updateStyle'         , path: TS.Config.Path.Utils        + 'updateStyle.js' },
  { name: 'localizationService' , path: TS.Config.Path.Services     + 'localizationService.js' },
  { name: 'ClickTouchHelper'    , path: TS.Config.Path.Utils        + 'ClickTouchHelper.js' },
  
  { name: 'ChannellistModel'    , path: TS.Config.Path.Models + 'ChannellistModel.js' },
  { name: 'ComscoreModel'       , path: TS.Config.Path.Models + 'ComscoreModel.js' },
  { name: 'ConfigModel'         , path: TS.Config.Path.Models + 'ConfigModel.js' },
  { name: 'CustomRulesModel'    , path: TS.Config.Path.Models + 'CustomRulesModel.js' },
  { name: 'PlaylistModel'       , path: TS.Config.Path.Models + 'PlaylistModel.js' },
  { name: 'QuantcastModel'      , path: TS.Config.Path.Models + 'QuantcastModel.js' },
  { name: 'VastCreative'        , path: TS.Config.Path.Models + 'VastCreative.js' },
  { name: 'VastModel'           , path: TS.Config.Path.Models + 'VastModel.js' },
  { name: 'VastMedia'           , path: TS.Config.Path.Models + 'VastMedia.js' },
  { name: 'LiverailModel'       , path: TS.Config.Path.Models + 'LiverailModel.js' },
  { name: 'AdtechModel'         , path: TS.Config.Path.Models + 'AdtechModel.js' },
    
  { name: 'initialize' 	},
  { name: 'facebookLink' },
  { name: 'carouselview' },
  { name: 'navigation' },
  { name: 'bannerview' 	},
  { name: 'preclipview' },
  { name: 'videoView' 	},
  { name: 'videoListener'},
  { name: 'postclipview'},
  { name: 'shareview'	},
  { name: 'closeAdView'}
];